version: '3.9'
services:
    fishfactory:
        image: fishfactory:latest
        ports:
            - "5000:5000"
        # Unmap these volumes to prevent storage of files on the host filesystem.
        volumes:
            - ./kits:/app/kits
            - ./screenshots:/app/screenshots
            - ./credstores:/app/credstores
            - ./favicons:/app/favicons